version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://form_user:form_password@mongodb:27017/formregistration?authSource=admin
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=form_user
      - MONGO_INITDB_ROOT_PASSWORD=form_password
      - MONGO_INITDB_DATABASE=formregistration
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    command: ["--auth"]

volumes:
  mongodb_data:
