version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/formregistration
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
